spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  servlet:
    context-path: /api
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}